/*
    * @author : Yan Nascimento
    * @Date : 2024/03/25
    * @Description : helper class to handle the trigger for Adopter object.
    * @log : 2024/03/25 - created
*/
public with sharing class AdopterTriggerHelper {
    public static void getAdopterNameToInsertOnAnimal(TriggerDataDTO triggerData) {
        System.debug('YNASC Inside getAdopterNameToInsertOnAnimal - triggerData'+triggerData);
        
    }
}