public with sharing class AdopterTriggerHelper {
    public AdopterTriggerHelper() {
        System.debug('Inside AdopterTriggerHelper Constructor');
    }
    public void getAdopterNameToInsertOnAnimal() {
        System.debug('Inside Task 1');
    }
    public void doTask2() {
        System.debug('Inside Task 2');
    }
    public void doTask3() {
        System.debug('Inside Task 3');
    }
    public void doTask4() {
        System.debug('Inside Task 4');
    }
    public void doTask5() {
        System.debug('Inside Task 5');
    }
}